spring :
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSH=false
   jpa:
    show-sql: true
server:
     context-path: /sell

wechat:
      mpAppId: wxd898fcb01713c658
      mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
      mchId:
      mchKey:
      mchPath: /var/weixin_cert/h5.p12
      notifyUrl: 域名/sell/pay/notify
# notifuUrl是支付的异步通知，非常重要
#logging:
 #   patter n:
  #      console: "%d - %msg%n"
   # path: /var/log/tomcat
    #file: /var/log/tomcat/sell.log
    #level: debug
